-- Enforce NOT NULL and constraints for cars and dealers
ALTER TABLE cars ALTER COLUMN make SET NOT NULL;
ALTER TABLE cars ALTER COLUMN model SET NOT NULL;
ALTER TABLE cars ALTER COLUMN price SET NOT NULL;
ALTER TABLE cars ALTER COLUMN dealer_id SET NOT NULL;
ALTER TABLE cars ALTER COLUMN city_id SET NOT NULL;
ALTER TABLE cars ALTER COLUMN fuel_type SET NOT NULL;
ALTER TABLE cars ALTER COLUMN id SET DATA TYPE uuid USING id::uuid;
ALTER TABLE cars ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE dealers ALTER COLUMN id SET DATA TYPE uuid USING id::uuid;
ALTER TABLE dealers ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE dealers ALTER COLUMN user_id SET NOT NULL;
