-- Add missing columns for Phase 9B
ALTER TABLE cars ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS profile_views INTEGER DEFAULT 0;
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS total_leads INTEGER DEFAULT 0;
